TARGET = make_lib

LIB_NAME = driver.a

OBJS =			\
	intc.o		\
	tmr.o		\
	uart.o		\
	gpio.o		\
	sata.o		\
	ata.o		\
	ataopt.o	\
	ataftl.o	\
	spi.o \
	smart.o		\
	ipm.o		\
	nand_sys.o \

CDEPS =			\
	



SUB_DIRS =

IMAGE_PATH_FLAGS =

PUBLISHED_LIB_PATH = $(PUBLIC_LIB_PATH)

include $(MAKE_RULES)
